import XCTest
import SwiftUI
import SnapshotTesting
import jLagunaDevMacro

@testable import Composable_SwiftUI

@SceneSnapshotUITest(scene: "LoadingView")
final class LoadingViewTests: XCTestCase {
    // Intentionally empty - tests code generated by Macros
}
