# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Run tests"
  lane :test do |options|
    scan(
      scheme: 'Composable SwiftUITests',
      device: ENV['DEVICE'],
      clean: true,
      code_coverage: true,
      result_bundle: true,
      derived_data_path: "fastlane/test_output",  # Asegúrate de que scan y xcov usen el mismo derived_data_path
      skip_testing: ['Composable SwiftUIUITests'],
      xcargs: "-skipPackagePluginValidation"
    )
  end

  desc "Generate coverage report"
  lane :generate_coverage_report do
    slather(
      coverage_xml: false,
      coverage_html: false,
      coverage_lcov: true,
      scheme: 'Composable SwiftUI',
      proj: 'Composable SwiftUI.xcodeproj',
      build_directory: "fastlane/test_output/build",
      output_directory: "fastlane/test_output/coverage",
      use_bundle_exec: true
    )
  end

end
