# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Run tests"
  lane :test do |options|
    scan(
      scheme: 'Composable SwiftUITests',
      device: 'iPhone 15',
      code_coverage: true,
      result_bundle: true,
      skip_testing: ['Composable SwiftUIUITests'],
	    clean: true,
      skip_package_dependencies_resolution: true,
      xcargs: "-skipPackagePluginValidation"
    )
  end

end
