name: iOS starter workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1.6.0
        with:
          xcode-version: latest-stable

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Xcode to Skip Macro Validation
        run: defaults write com.apple.dt.Xcode IDESkipMacroFingerprintValidation -bool YES

      - name: Install SwiftLint
        run: |
          brew install swiftlint

      - name: Build and Test
        run: |
          xcodebuild -scheme "Composable SwiftUI" \
                     -project "Composable SwiftUI.xcodeproj" \
                     -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.0' \
                     -skipPackagePluginValidation \
                     -allowProvisioningUpdates \
                     clean build test | xcpretty
