name: iOS starter workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Run test using Fastlane
    runs-on: ${{ matrix.MACOS_VERSION }}

    strategy:
      matrix:
        macos_version: [macos-14]
        xcode_version: ['16.0.0'] #https://github.com/actions/runner-images/blob/main/images/macos/macos-14-arm64-Readme.md#xcode
        iphone_model: ['iPhone 14']

    steps:
      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1.6.0
        with:
          xcode-version: ${{ matrix.XCODE_VERSION }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0

      - name: Install Fastlane
        run: gem install fastlane

      - name: Install Bundler
        run: gem install bundler

      - name: Install dependencies
        run: bundle install

      - name: Set Xcode to Skip Macro Validation
        run: defaults write com.apple.dt.Xcode IDESkipMacroFingerprintValidation -bool YES

      - name: Run Fastlane
        env:
          DEVICE: ${{ matrix.IPHONE_MODEL }}
        run: |
          export FASTLANE_XCODEBUILD_SETTINGS_RETRIES=10
          bundle exec fastlane test
